services:
  - type: web
    name: affiliatebot-pro
    env: python
    buildCommand: pip install flask
    startCommand: python render_app.py
    plan: free
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"