services:
  - type: web
    name: affiliatebot-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: affiliatebot-database
          property: connectionString
  
  - type: pserv
    name: affiliatebot-database
    env: postgresql
    plan: free
    databaseName: affiliatebot_db
    databaseUser: affiliatebot_user