services:
  - type: web
    name: affiliatebot-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: affiliatebot-db
          property: connectionString
      - key: RENDER
        value: "true"
      - key: REPLIT_DEPLOYMENT
        value: "true"

  - type: pgsql
    name: affiliatebot-db
    databaseName: affiliatebot
    user: affiliatebot
    plan: free